### ISSUE TITLE
final consonant ㅇ + initial consonant ㅇ combination deleting the final consonant

### ISSUE THREAD

**Issue by s67112** [osori/korean-romanizer#10]
for example, '강약' would produce 'gayak'
강원 would be 'gawon'

**Comment by osori** [comment]
There was indeed a problem handling syllables with initial consonant ㅇ, and I just made a fix. It now works for both examples you provided. Thank you so much for reporting this issue!

**Comment by s67112** [comment]
wow, thanks so much for fixing it so quickly!
